theme: jekyll-theme-minimal
title: Wairarapa Dark Sky Society
description: The Martinborough Dark Sky Society is a community initiative to protect and enhance the beautiful dark skies and natural wildlife habitats we enjoy.
